package apiv1

import "uuid"

// Ids cross the API boundary as canonical UUID text and become uuid.UUID
// inside. The spec pins every id parameter and property to the UUID pattern,
// and the request-validation middleware (see validate.go) rejects anything
// that does not match before a handler runs — so by the time toID sees a
// string it is already well-formed.
//
// A malformed id is therefore not a case handlers branch on: it cannot exist,
// so it cannot match a row. toID maps it to the nil UUID, which no row ever
// carries (the schema's CHECK forbids it and every id is generated by
// uuid.NewV4), and the lookup that follows returns the same 404 any other
// unknown id would. That keeps "malformed" and "not yours" indistinguishable,
// which is the same non-disclosure the rest of the API is careful about.
func toID(s string) uuid.UUID {
	u, err := uuid.Parse(s)
	if err != nil {
		return uuid.Nil()
	}
	return u
}

// optToID is toID for an optional wire id: absent stays absent, which is what
// makes a role assignment system-scoped rather than tenant-scoped.
func optToID(s *string) *uuid.UUID {
	if s == nil {
		return nil
	}
	u := toID(*s)
	return &u
}

// optIDString is the reverse, for rendering an optional id back onto the wire.
func optIDString(u *uuid.UUID) *string {
	if u == nil {
		return nil
	}
	s := u.String()
	return &s
}
